const tabs=document.querySelectorAll('.tab'),login=document.getElementById('loginForm'),register=document.getElementById('registerForm'),msg=document.getElementById('authMsg');
function showMsg(text,error=false){msg.textContent=text;msg.className=`form-msg ${error?'error':'success'}`}
function digits(v){return String(v||'').replace(/\D/g,'')}
function maskCnpj(v){const d=digits(v).slice(0,14);return d.replace(/(\d{2})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1/$2').replace(/(\d{4})(\d{1,2})$/,'$1-$2')}
const cnpj=document.getElementById('registerCnpj');if(cnpj)cnpj.addEventListener('input',()=>{cnpj.value=maskCnpj(cnpj.value);lookupRegisterCompany()});
async function lookupRegisterCompany(){const d=digits(cnpj?.value);const box=document.getElementById('companyLookup');if(!box)return;if(d.length!==14){box.textContent='Digite o CNPJ para verificar se a empresa já está cadastrada.';box.className='lookup-box';return}try{const r=await fetch(`/api/v1/companies/lookup/${d}`);const data=await r.json();if(r.ok&&data.found){document.getElementById('registerCompany').value=data.company.tradeName;document.getElementById('registerLegalName').value=data.company.legalName;box.textContent='Empresa encontrada. Este cadastro enviará uma solicitação de acesso ao administrador.';box.className='lookup-box found';}else{box.textContent='CNPJ disponível. Você será o primeiro administrador desta empresa.';box.className='lookup-box available';}}catch{box.textContent='Não foi possível consultar o CNPJ agora.';box.className='lookup-box'} }
tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');const r=t.dataset.auth==='register';login.classList.toggle('hidden',r);register.classList.toggle('hidden',!r);msg.textContent=''});
async function submitAuth(url,payload){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível concluir.');return d}
login.onsubmit=async e=>{e.preventDefault();try{const data=await submitAuth('/api/v1/auth/login',{email:document.getElementById('loginEmail').value,password:document.getElementById('loginPassword').value});sessionStorage.setItem('pc_token',data.token);sessionStorage.setItem('pc_user',JSON.stringify(data.user));location.href='index.html'}catch(err){showMsg(err.message,true)}};
register.onsubmit=async e=>{e.preventDefault();if(document.getElementById('registerPassword').value!==document.getElementById('registerConfirm').value)return showMsg('As senhas não coincidem.',true);const c=digits(cnpj.value);const existing=document.getElementById('companyLookup')?.classList.contains('found');const url=existing?'/api/v1/companies/join':'/api/v1/companies/register';const payload={name:document.getElementById('registerName').value,cnpj:c,companyName:document.getElementById('registerCompany').value,tradeName:document.getElementById('registerCompany').value,legalName:document.getElementById('registerLegalName').value,email:document.getElementById('registerEmail').value,password:document.getElementById('registerPassword').value,role:document.getElementById('registerRole').value};try{const data=await submitAuth(url,payload);if(data.token){sessionStorage.setItem('pc_token',data.token);sessionStorage.setItem('pc_user',JSON.stringify(data.user));location.href='index.html';}else{showMsg(data.message||'Solicitação enviada. Aguarde a aprovação do administrador.');register.reset();}}catch(err){showMsg(err.message,true)}};
