function animateNumber(el,end,duration=800){if(!el)return;const start=performance.now();function tick(now){const p=Math.min((now-start)/duration,1);el.textContent=Math.round(end*p).toLocaleString('pt-BR');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function animateMoney(el,end,duration=900){if(!el)return;const start=performance.now();function tick(now){const p=Math.min((now-start)/duration,1);el.textContent=money(end*p);if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
function renderDashboard(items){const demand=items.reduce((s,p)=>s+p.forecast,0),production=items.reduce((s,p)=>s+Number(p.currentProduction),0),surplus=items.reduce((s,p)=>s+p.surplus,0),saving=items.reduce((s,p)=>s+p.saving,0);animateNumber(document.getElementById('kpi-demand'),demand);animateNumber(document.getElementById('kpi-production'),production);animateNumber(document.getElementById('kpi-surplus'),surplus);animateMoney(document.getElementById('kpi-saving'),saving);document.getElementById('periods-label').textContent=items.reduce((s,p)=>s+p.rows.length,0)+' registros';const tb=document.getElementById('productsTable');tb.innerHTML=items.length?items.map(p=>`<tr class="${p.surplus>0?'excess':''}"><td><b>${escapeHtml(p.name)}</b></td><td>${escapeHtml(p.unit)}</td><td class="mono">${fmt(p.forecast)}</td><td class="mono">${fmt(p.currentProduction)}</td><td class="mono">${fmt(p.surplus)}</td><td><span class="badge ${p.surplus>0?'amber':'green'}">${p.surplus>0?'Excedente':'Equilibrado'}</span></td></tr>`).join(''):'<tr><td colspan="6" class="empty">Nenhum produto cadastrado.</td></tr>';document.getElementById('summaryBox').innerHTML=`<div class="summary-line"><span>Produtos analisados</span><b>${items.length}</b></div><div class="summary-line"><span>Demanda total prevista</span><b>${fmt(demand)}</b></div><div class="summary-line"><span>Produção total</span><b>${fmt(production)}</b></div><div class="summary-line"><span>Economia potencial</span><b>${money(saving)}</b></div>`;drawChart(items)}
function drawChart(items){
 const canvas=document.getElementById('demandChart');if(!canvas)return;
 const ctx=canvas.getContext('2d'),w=canvas.clientWidth||600,h=230,dpr=devicePixelRatio||1;
 canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);
 const rows=items[0]?.rows||[];
 if(!rows.length){ctx.fillStyle='#66717d';ctx.font='14px IBM Plex Sans';ctx.fillText('Adicione histórico de vendas para visualizar a previsão.',20,40);return}
 const vals=rows.slice(-6).map(r=>Number(r.quantity)),forecast=items[0].forecast,max=Math.max(...vals,forecast)*1.15,min=Math.min(...vals,forecast)*.85||1;
 const x=i=>30+i*((w-55)/Math.max(vals.length,1)),y=v=>h-25-(v-min)/(max-min)*(h-50);
 const started=performance.now();
 function frame(now){
   const progress=Math.min(1,(now-started)/650),ease=1-Math.pow(1-progress,3);
   ctx.clearRect(0,0,w,h);ctx.strokeStyle='#d7d3cc';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(30,10);ctx.lineTo(30,h-25);ctx.lineTo(w-15,h-25);ctx.stroke();
   ctx.strokeStyle='#2F6FB0';ctx.lineWidth=2.5;ctx.beginPath();
   vals.forEach((v,i)=>{const yy=h-25-((h-25-y(v))*ease);i?ctx.lineTo(x(i),yy):ctx.moveTo(x(i),yy)});ctx.stroke();
   ctx.fillStyle='#2F6FB0';vals.forEach((v,i)=>{const yy=h-25-((h-25-y(v))*ease);ctx.beginPath();ctx.arc(x(i),yy,4,0,Math.PI*2);ctx.fill()});
   const fx=x(vals.length);ctx.setLineDash([5,5]);ctx.strokeStyle='#4C7A5E';ctx.beginPath();ctx.moveTo(fx,10);ctx.lineTo(fx,h-25);ctx.stroke();ctx.setLineDash([]);
   const fy=h-25-((h-25-y(forecast))*ease);ctx.fillStyle='#4C7A5E';ctx.beginPath();ctx.arc(fx,fy,5,0,Math.PI*2);ctx.fill();ctx.font='12px IBM Plex Mono';ctx.fillText('PREVISÃO',Math.min(fx+7,w-80),Math.max(15,fy-8));
   if(progress<1)requestAnimationFrame(frame);
 }
 requestAnimationFrame(frame);
}
async function renderProductsPage(){
  const form=document.getElementById('productForm'),box=document.getElementById('ingredients'),add=document.getElementById('addIngredient'),list=document.getElementById('productsList');
  let editingId=null,products=[],stockItems=[];
  const fields=()=>({name:document.getElementById('productName'),unit:document.getElementById('productUnit'),production:document.getElementById('productProduction'),cost:document.getElementById('productCost')});
  function addRow(data={}){const d=document.createElement('div');d.className='ingredient-row';d.innerHTML=`<select class="ing-material"><option value="">Vincular matéria-prima</option>${stockItems.map(x=>`<option value="${x.id}" ${Number(data.rawMaterialId)===Number(x.id)?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select><input class="ing-name" placeholder="Nome do insumo" value="${escapeHtml(data.name||'')}"><input class="ing-cost" type="number" min="0" step="0.01" placeholder="Custo unit." value="${data.unitCost??''}"><input class="ing-qty" type="number" min="0" step="0.01" placeholder="Qtd/produto" value="${data.quantityPerProduct??''}"><input class="ing-waste" type="number" min="0" step="0.1" placeholder="% desperdício" value="${data.wastePercent??''}"><button type="button" class="btn" title="Remover">×</button>`;d.querySelector('button').onclick=()=>d.remove();box.appendChild(d)}
  function fillForm(p){editingId=p.id;const f=fields();f.name.value=p.name;f.unit.value=p.unit;f.production.value=p.currentProduction;f.cost.value=p.unitCost;box.innerHTML='';(p.ingredients||[]).forEach(addRow);if(!(p.ingredients||[]).length)addRow();document.getElementById('formTitle').textContent='Editar produto';document.getElementById('saveProductBtn').textContent='Salvar alterações';document.getElementById('cancelEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
  function clearForm(){editingId=null;form.reset();box.innerHTML='';addRow();document.getElementById('formTitle').textContent='Novo produto';document.getElementById('saveProductBtn').textContent='Salvar produto';document.getElementById('cancelEdit').classList.add('hidden');document.getElementById('productMsg').textContent=''}
  function ingredientPayload(){return [...box.querySelectorAll('.ingredient-row')].map(r=>({rawMaterialId:Number(r.querySelector('.ing-material').value)||null,name:r.querySelector('.ing-name').value.trim(),unitCost:Number(r.querySelector('.ing-cost').value)||0,quantityPerProduct:Number(r.querySelector('.ing-qty').value)||0,wastePercent:Number(r.querySelector('.ing-waste').value)||0})).filter(x=>x.name)}
  async function load(){[products,stockItems]=await Promise.all([getProducts(),getStock()]);list.innerHTML=products.length?products.map(p=>`<tr><td><b>${escapeHtml(p.name)}</b></td><td>${escapeHtml(p.unit)}</td><td class="mono">${fmt(p.currentProduction)}</td><td class="mono">${money(p.unitCost)}</td><td><div class="table-actions"><button class="btn small" data-edit="${p.id}">Editar</button><button class="btn small danger" data-delete="${p.id}">Excluir</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum produto cadastrado.</td></tr>';list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>fillForm(products.find(p=>Number(p.id)===Number(b.dataset.edit))));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este produto? O histórico relacionado também poderá ser removido.'))return;try{await deleteProduct(b.dataset.delete);if(Number(editingId)===Number(b.dataset.delete))clearForm();await load()}catch(e){alert(e.message)}})}
  add.onclick=()=>addRow();document.getElementById('cancelEdit').onclick=clearForm;await load();box.innerHTML='';addRow();
  form.onsubmit=async e=>{e.preventDefault();const f=fields();const payload={name:f.name.value.trim(),unit:f.unit.value,currentProduction:Number(f.production.value)||0,unitCost:Number(f.cost.value)||0,ingredients:ingredientPayload()};const msg=document.getElementById('productMsg');try{if(!payload.name)throw new Error('Informe o nome do produto.');if(editingId)await updateProduct(editingId,payload);else await createProduct(payload);msg.textContent=editingId?'Produto atualizado no banco de dados.':'Produto cadastrado no banco de dados.';await load();if(editingId)clearForm();else{form.reset();box.innerHTML='';addRow()}}catch(err){msg.textContent=err.message;msg.style.color='var(--terracota)'}}
}

function renderSales(){const tb=document.getElementById('salesTable');if(!tb)return;let products=[],sales=[];const draw=()=>{tb.innerHTML=sales.length?sales.map(s=>`<tr><td><input class="table-input" data-field="period" data-id="${s.id}" value="${escapeHtml(s.period)}"></td><td>${escapeHtml(s.productName)}</td><td><input class="table-input number" data-field="quantity" data-id="${s.id}" type="number" min="0" step="1" value="${s.quantity}"></td><td><span class="badge green">Salvo</span></td></tr>`).join(''):'<tr><td colspan="4" class="empty">Nenhum histórico cadastrado.</td></tr>'};Promise.all([getProducts(),getSalesHistories()]).then(([p,s])=>{products=p;sales=s;draw()});document.getElementById('saveSales').onclick=async()=>{try{for(const s of sales){const period=tb.querySelector(`[data-id="${s.id}"][data-field="period"]`)?.value;const quantity=tb.querySelector(`[data-id="${s.id}"][data-field="quantity"]`)?.value;if(period)await updateSale(s.id,{productId:s.productId,period,quantity:Number(quantity)||0})}document.getElementById('salesMsg').textContent='Alterações salvas no banco de dados.';sales=await getSalesHistories();draw()}catch(e){document.getElementById('salesMsg').textContent=e.message}};document.getElementById('addSale').onclick=()=>{if(!products.length)return alert('Cadastre um produto primeiro.');const now=new Date();const period=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;saveSale({productId:products[0].id,period,quantity:0}).then(()=>getSalesHistories()).then(s=>{sales=s;draw()}).catch(e=>alert(e.message))};document.getElementById('csvFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{const lines=String(reader.result).split(/\r?\n/).filter(Boolean),rows=[];for(let i=1;i<lines.length;i++){const [period,product,quantity]=lines[i].split(',').map(x=>x.trim());rows.push({period,product,quantity})}try{const result=await importSales(rows);document.getElementById('csvFeedback').innerHTML=`<div class="notice">${result.imported} linha(s) importada(s). ${result.errors?.length||0} erro(s).</div>`;sales=await getSalesHistories();draw()}catch(err){document.getElementById('csvFeedback').innerHTML=`<div class="notice warning-note">${escapeHtml(err.message)}</div>`}};reader.readAsText(file)}}
function renderBuyers(){const tb=document.getElementById('buyersTable');if(!tb)return;let buyers=[];const draw=()=>tb.innerHTML=buyers.map(b=>`<tr><td><b>${escapeHtml(b.name)}</b></td><td>${escapeHtml(b.frequency)}</td><td class="mono">${fmt(b.averageVolume)}</td><td><div class="table-actions"><button class="btn small" data-edit-buyer="${b.id}">Editar</button><button class="btn small danger" data-delete-buyer="${b.id}">Excluir</button></div></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Nenhum comprador cadastrado.</td></tr>';getBuyers().then(b=>{buyers=b;draw()});document.getElementById('buyerForm').onsubmit=async e=>{e.preventDefault();try{await createBuyer({name:document.getElementById('buyerName').value,frequency:document.getElementById('buyerFrequency').value,averageVolume:Number(document.getElementById('buyerVolume').value)});document.getElementById('buyerMsg').textContent='Comprador cadastrado no banco de dados.';e.target.reset();buyers=await getBuyers();draw()}catch(err){document.getElementById('buyerMsg').textContent=err.message}};tb.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-buyer]'),del=e.target.closest('[data-delete-buyer]');if(edit){const b=buyers.find(x=>Number(x.id)===Number(edit.dataset.editBuyer));const name=prompt('Nome do comprador:',b.name);if(name===null)return;const volume=prompt('Volume médio:',b.averageVolume);if(volume===null)return;try{await updateBuyer(b.id,{name,frequency:b.frequency,averageVolume:Number(volume)||0});buyers=await getBuyers();draw()}catch(err){alert(err.message)}}if(del&&confirm('Excluir comprador?')){await deleteBuyer(del.dataset.deleteBuyer);buyers=await getBuyers();draw()}})}
function renderCpp(items){const d=items.reduce((s,p)=>s+p.forecast,0),pr=items.reduce((s,p)=>s+Number(p.currentProduction),0),su=items.reduce((s,p)=>s+p.surplus,0),sa=items.reduce((s,p)=>s+p.saving,0);const a=document.getElementById('cppDemand'),b=document.getElementById('cppProduction'),c=document.getElementById('cppSurplus'),dEl=document.getElementById('cppSaving');if(a)a.textContent=fmt(d);if(b)b.textContent=fmt(pr);if(c)c.textContent=fmt(su);if(dEl)dEl.textContent=money(sa);const tb=document.getElementById('cppTable');if(tb)tb.innerHTML=items.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td class="mono">${fmt(p.surplus)}</td><td class="mono">${money(p.unitCost)}</td><td class="mono">${money(p.saving)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Nenhum dado disponível.</td></tr>'}
async function renderDashboardControl(){const root=document.getElementById('controlMetrics');if(!root)return;try{const r=await getManagementReport();const o=r.orders||{},s=r.stock||{},c=r.cpp||{},v=r.sales||{};document.getElementById('dash-open-orders').textContent=Number(o.open||0).toLocaleString('pt-BR');document.getElementById('dash-low-stock').textContent=Number(s.lowStock||0).toLocaleString('pt-BR');document.getElementById('dash-cpp-saving').textContent=money(c.saving);document.getElementById('dash-sales').textContent=fmt(v.total)}catch{}}
