const router=require('express').Router();
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {get,run}=require('../db/database');
const {auth,secret}=require('../middleware/auth');
function makeToken(u){return jwt.sign({id:u.id,name:u.name,email:u.email,companyId:u.companyId,companyName:u.companyName,role:u.role,status:u.status},secret,{expiresIn:'7d'});}
function publicUser(u){return{id:u.id,name:u.name,companyName:u.companyName,email:u.email,companyId:u.companyId,role:u.role,status:u.status};}
router.post('/login',async(req,res,next)=>{try{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');const u=await get('SELECT u.*,c.trade_name AS companyName,c.status AS companyStatus FROM users u LEFT JOIN companies c ON c.id=u.company_id WHERE u.email=?',[email]);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'E-mail ou senha inválidos'});if(u.status==='pending')return res.status(403).json({error:'Seu acesso está aguardando aprovação do administrador da empresa.'});if(u.status==='blocked')return res.status(403).json({error:'Seu acesso está bloqueado. Procure o administrador da empresa.'});if(!u.company_id)return res.status(403).json({error:'Sua conta não possui uma empresa vinculada.'});if(u.companyStatus!=='active')return res.status(403).json({error:'A empresa está suspensa.'});const user=publicUser(u);res.json({user,token:makeToken(user)});}catch(e){next(e)}});
router.get('/me',auth,async(req,res,next)=>{try{const u=await get('SELECT u.id,u.name,u.email,u.company_id AS companyId,u.role,u.status,c.trade_name AS companyName,c.cnpj,c.legal_name AS legalName,c.status AS companyStatus FROM users u LEFT JOIN companies c ON c.id=u.company_id WHERE u.id=?',[req.user.id]);if(!u)return res.status(404).json({error:'Usuário não encontrado'});res.json({user:publicUser(u),company:{id:u.companyId,cnpj:u.cnpj,legalName:u.legalName,tradeName:u.companyName,status:u.companyStatus}});}catch(e){next(e)}});

router.put('/password',auth,async(req,res,next)=>{try{const current=String(req.body?.currentPassword||''),nextPassword=String(req.body?.newPassword||'');if(nextPassword.length<6)return res.status(400).json({error:'A nova senha precisa ter pelo menos 6 caracteres'});const u=await get('SELECT password_hash FROM users WHERE id=?',[req.user.id]);if(!u||!(await bcrypt.compare(current,u.password_hash)))return res.status(400).json({error:'Senha atual incorreta'});const hash=await bcrypt.hash(nextPassword,12);await run('UPDATE users SET password_hash=? WHERE id=?',[hash,req.user.id]);res.json({ok:true,message:'Senha alterada com sucesso.'});}catch(e){next(e)}});
router.put('/me',auth,async(req,res,next)=>{try{const {name,email}=req.body||{};if(!name||!email)return res.status(400).json({error:'Nome e e-mail são obrigatórios'});const e=String(email).trim().toLowerCase();const exists=await get('SELECT id FROM users WHERE email=? AND id<>?',[e,req.user.id]);if(exists)return res.status(409).json({error:'E-mail já utilizado por outra conta'});await run('UPDATE users SET name=?,email=? WHERE id=?',[String(name).trim(),e,req.user.id]);const u=await get('SELECT u.id,u.name,u.email,u.company_id AS companyId,u.role,u.status,c.trade_name AS companyName,c.status AS companyStatus FROM users u LEFT JOIN companies c ON c.id=u.company_id WHERE u.id=?',[req.user.id]);const user=publicUser(u);res.json({user,token:makeToken(user)});}catch(e){next(e)}});
module.exports={router,makeToken,publicUser};
