const router=require('express').Router();
const {run,get,all,transaction}=require('../db/database');
const {auth,requireRole,issueSession}=require('../middleware/auth');
const {rateLimit,validPassword,validEmail}=require('../middleware/security');
const ah=require('../utils/asyncHandler');
const {companyId,audit}=require('../utils/tenant');
function normalizeCnpj(v){return String(v||'').replace(/\D/g,'');}
function validCnpj(v){const c=normalizeCnpj(v);if(c.length!==14||/^([0-9])\1+$/.test(c))return false;let sum=0;for(let i=0;i<12;i++)sum+=Number(c[i])*(i<4?5-i:13-i);let d=sum%11<2?0:11-sum%11;if(d!==Number(c[12]))return false;sum=0;for(let i=0;i<13;i++)sum+=Number(c[i])*(i<5?6-i:14-i);d=sum%11<2?0:11-sum%11;return d===Number(c[13]);}
router.get('/lookup/:cnpj',rateLimit('company-lookup',30,900),ah(async(req,res)=>{const cnpj=normalizeCnpj(req.params.cnpj);if(!validCnpj(cnpj))return res.status(400).json({error:'CNPJ inválido'});const c=await get("SELECT id,cnpj,legal_name AS legalName,trade_name AS tradeName,status FROM companies WHERE cnpj=? AND cnpj NOT LIKE 'LEGACY%'",[cnpj]);if(!c)return res.status(404).json({found:false});res.json({found:true,company:{id:c.id,cnpj:c.cnpj,legalName:c.legalName,tradeName:c.tradeName,status:c.status}})}));
router.get('/me',auth,ah(async(req,res)=>{const c=await get('SELECT id,cnpj,legal_name AS legalName,trade_name AS tradeName,email,phone,street,number,complement,neighborhood,city,state,status,created_at AS createdAt FROM companies WHERE id=?',[companyId(req)]);if(!c)return res.status(404).json({error:'Empresa não encontrada'});res.json({company:c})}));
router.put('/me',auth,requireRole('admin'),ah(async(req,res)=>{const cid=companyId(req);const b=req.body||{};const fields={legalName:String(b.legalName||'').trim(),tradeName:String(b.tradeName||'').trim(),email:String(b.email||'').trim().toLowerCase(),phone:String(b.phone||'').trim(),street:String(b.street||'').trim(),number:String(b.number||'').trim(),complement:String(b.complement||'').trim(),neighborhood:String(b.neighborhood||'').trim(),city:String(b.city||'').trim(),state:String(b.state||'').trim().toUpperCase()};if(!fields.legalName||!fields.tradeName)return res.status(400).json({error:'Razão social e nome fantasia são obrigatórios'});await run('UPDATE companies SET legal_name=?,trade_name=?,email=?,phone=?,street=?,number=?,complement=?,neighborhood=?,city=?,state=? WHERE id=?',[...Object.values(fields),cid]);await run('UPDATE users SET company_name=? WHERE company_id=?',[fields.tradeName,cid]);await audit(req,'update','company',cid,{tradeName:fields.tradeName});res.json({ok:true})}));
router.post('/register',rateLimit('registration',5,3600),ah(async(req,res,next)=>{try{const b=req.body||{};const name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),cnpj=normalizeCnpj(b.cnpj),legalName=String(b.legalName||b.companyName||'').trim(),tradeName=String(b.tradeName||b.companyName||'').trim();if(!name||!validEmail(email)||!validPassword(password)||!validCnpj(cnpj)||!legalName||!tradeName)return res.status(400).json({error:'Informe nome, CNPJ válido, empresa e senha com pelo menos 12 caracteres (máximo 72 bytes)'});const exists=await get('SELECT id FROM users WHERE email=?',[email]);if(exists)return res.status(409).json({error:'E-mail já cadastrado'});const c=await get('SELECT id FROM companies WHERE cnpj=?',[cnpj]);if(c)return res.status(409).json({error:'Já existe uma empresa com este CNPJ. Use “Entrar em empresa”.'});const bcrypt=require('bcryptjs');const hash=await bcrypt.hash(password,12);const result=await transaction(async(tx)=>{const cr=await tx.run('INSERT INTO companies(cnpj,legal_name,trade_name,email,phone) VALUES(?,?,?,?,?)',[cnpj,legalName,tradeName,email,String(b.phone||'').trim()]);const ur=await tx.run("INSERT INTO users(name,company_name,email,password_hash,company_id,role,status) VALUES(?,?,?,?,?,'admin','active')",[name,tradeName,email,hash,cr.id]);return{companyId:cr.id,userId:ur.id};});const u={id:result.userId,name,companyName:tradeName,email,companyId:result.companyId,role:'admin',status:'active'};const token=await issueSession(req,res,u.id,hash);res.status(201).json({user:u,...(token?{token}:{}),company:{id:result.companyId,cnpj,legalName,tradeName}});}catch(e){next(e)}}));
router.post('/join',rateLimit('registration',5,3600),ah(async(req,res)=>{const b=req.body||{};const name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),cnpj=normalizeCnpj(b.cnpj),requestedRole=['production','commercial','viewer'].includes(b.role)?b.role:'viewer';if(!name||!validEmail(email)||!validPassword(password)||!validCnpj(cnpj))return res.status(400).json({error:'Informe nome, e-mail, CNPJ válido e senha com pelo menos 12 caracteres (máximo 72 bytes)'});const company=await get("SELECT id,trade_name AS tradeName,status FROM companies WHERE cnpj=? AND cnpj NOT LIKE 'LEGACY%'",[cnpj]);if(!company)return res.status(404).json({error:'Empresa não encontrada. Cadastre a empresa primeiro.'});if(company.status!=='active')return res.status(403).json({error:'Esta empresa está suspensa'});if(await get('SELECT id FROM users WHERE email=?',[email]))return res.status(409).json({error:'E-mail já cadastrado'});const bcrypt=require('bcryptjs');const hash=await bcrypt.hash(password,12);const r=await transaction(async(tx)=>{const u=await tx.run("INSERT INTO users(name,company_name,email,password_hash,company_id,role,status) VALUES(?,?,?,?,?,'viewer','pending')",[name,company.tradeName,email,hash,company.id]);await tx.run('UPDATE users SET role=? WHERE id=?',[requestedRole,u.id]);await tx.run('INSERT INTO company_join_requests(company_id,user_id,requested_role) VALUES(?,?,?)',[company.id,u.id,requestedRole]);return u;});res.status(201).json({pending:true,message:'Solicitação enviada. Um administrador da empresa precisa aprovar seu acesso.',requestId:r.id});}));
module.exports=router;
