const router=require('express').Router();
const {run,all,get}=require('../db/database');
const {auth,requireRole}=require('../middleware/auth');
const ah=require('../utils/asyncHandler'); const {companyId,audit}=require('../utils/tenant');
router.get('/',auth,ah(async(req,res)=>{const rows=await all(`SELECT pl.id,pl.product_id AS productId,p.name AS productName,pl.period,pl.planned_quantity AS plannedQuantity,pl.target_sales AS targetSales,pl.priority,pl.status,pl.note,pl.created_at AS createdAt FROM production_plans pl JOIN products p ON p.id=pl.product_id WHERE pl.company_id=? ORDER BY pl.period DESC,FIELD(pl.priority,'high','medium','low'),pl.id DESC`,[companyId(req)]);res.json(rows.map(r=>({...r,id:Number(r.id),productId:Number(r.productId),plannedQuantity:Number(r.plannedQuantity),targetSales:Number(r.targetSales)})))}));
router.post('/',auth,requireRole('admin','production','commercial'),ah(async(req,res)=>{const b=req.body||{},productId=Number(b.productId),planned=Number(b.plannedQuantity)||0,target=Number(b.targetSales)||0,period=String(b.period||'').trim();if(!productId||!/^[0-9]{4}-[0-9]{2}$/.test(period))return res.status(400).json({error:'Produto e período (AAAA-MM) são obrigatórios.'});const p=await get('SELECT id FROM products WHERE id=? AND company_id=?',[productId,companyId(req)]);if(!p)return res.status(404).json({error:'Produto não encontrado'});const r=await run(`INSERT INTO production_plans(company_id,user_id,product_id,period,planned_quantity,target_sales,priority,status,note) VALUES(?,?,?,?,?,?,?,?,?)`,[companyId(req),req.user.id,productId,period,planned,target,['high','medium','low'].includes(b.priority)?b.priority:'medium','planned',String(b.note||'')]);await audit(req,'create','production_plan',r.id,{period});res.status(201).json({id:r.id})}));
router.patch('/:id',auth,requireRole('admin','production','commercial'),ah(async(req,res)=>{const id=Number(req.params.id),b=req.body||{};const r=await run(`UPDATE production_plans SET planned_quantity=COALESCE(?,planned_quantity),target_sales=COALESCE(?,target_sales),priority=COALESCE(?,priority),status=COALESCE(?,status),note=COALESCE(?,note) WHERE id=? AND company_id=?`,[b.plannedQuantity===undefined?null:Number(b.plannedQuantity)||0,b.targetSales===undefined?null:Number(b.targetSales)||0,['high','medium','low'].includes(b.priority)?b.priority:null,['planned','in_progress','done','cancelled'].includes(b.status)?b.status:null,b.note===undefined?null:String(b.note),id,companyId(req)]);if(!r.changes)return res.status(404).json({error:'Planejamento não encontrado'});await audit(req,'update','production_plan',id,b);res.json({ok:true})}));
router.delete('/:id',auth,requireRole('admin'),ah(async(req,res)=>{const r=await run('DELETE FROM production_plans WHERE id=? AND company_id=?',[Number(req.params.id),companyId(req)]);if(!r.changes)return res.status(404).json({error:'Planejamento não encontrado'});res.json({ok:true})}));
module.exports=router;
